### ISSUE TITLE
Mod Homepage, Mod Config File, Mod Folder do not open (v 0.5.0 and 0.5.1)

### ISSUE THREAD

**Issue by hughesjr** [erkle64/FoundryModManager#3]
The Mod Home page, Mod Config file and Mod Folder do not open for me.

I did my install in D:\FoundryModManager\ and not in 'program files'.

The game does launch fine and the program finds the game without problems on install.

The auto upgrade from v 0.5.0 to 0.5.1 did work .. but it tried to install in C:\Progrsm Files\ and not D:\

I installed from the MSI installer.

This is on Windows 11 .. latest update set.

Link from Tweaks tab and Open folder from Settings tab DO work OK.

**Comment by erkle64** [comment]
Thanks for the report.
They all use the same code.  Did you have a mod selected in the left window when clicking the buttons that didn't work?

**Comment by hughesjr** [comment]
I do have the program selected .. Also, If I put files in the tweaks directory that works fine (Once I figured out where it was).

I can try installing in the default 'program files' and see if that matters.

**Comment by erkle64** [comment]
I've tried installing to the same location as you already.  Didn't break anything for me.
I'm just trying to rule out the possibility that you didn't select a mod before clicking the buttons.  If you don't see a blue bar in the mod list, and a description below it, the buttons aren't meant to work.  Although I should make them greyed out to indicate that,

**Comment by hughesjr** [comment]
It retains all the functionality so is not a huge problem.  I don't see any errors in the Windows Event Log or the Windows Defender Log.

**Comment by hughesjr** [comment]
OK .. v0.5.2 fixed my issue and I am an Idiot :) .. I thought I had the individual mod selected, but obviously I did not.  Now it doesn't work unless I have it selected.  We can close this issue.
